platform :ios, '8.0'

target 'BWiOSComponentsSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 4.0.0'
  pod 'SDWebImage', '~> 4.2.2'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', '~> 4.0.0'

end
