platform :ios, '8.0'

target 'BWiOSComponents' do
  
pod 'Masonry', '~> 1.0.2'
pod 'FMDB', '~> 2.6.2'
pod 'SDWebImage', '~> 4.1.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'iCarousel', '~> 1.8.3'
pod 'SDCycleScrollView', '~> 1.73'

end
