platform :ios, '8.0'

target 'BWiOSComponents' do
  
pod 'Masonry', '~> 1.0.2'
pod 'FMDB', '~> 2.6.2'
pod 'SDWebImage', '~> 4.0.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'iCarousel', '~> 1.8.3'
pod 'SDCycleScrollView', '~> 1.73'
pod 'CXAlertView', '~> 1.1.0'
pod 'FLAnimatedImage', '~> 1.0.12'
pod 'TMCache', '~> 2.1.0'
pod 'pop', '~> 1.0.10'

end
