platform :ios, '8.0'

target 'BWiOSComponents' do
  
    pod 'Masonry', '1.0.2'
    pod 'FMDB', '2.6.2'
    pod 'SDWebImage', '4.0.0'
    pod 'AFNetworking', '3.1.0'
    pod 'iCarousel', '1.8.3'
    pod 'SDCycleScrollView', '1.73'
    pod 'CXAlertView', '1.1.0'
    pod 'FLAnimatedImage', '1.0.12'
    pod 'TMCache', '2.1.0'
    pod 'pop', '1.0.10'
    pod 'XXNibBridge', '2.3.1'
    pod 'YYCategories', '1.0.4'
    pod 'SVProgressHUD', '2.1.2'
    
    pod 'UPPaySDK', '3.3.6'  # 银联支付控件
    pod 'UMengUShare/Social/WeChat', '6.4.5'  # 友盟-微信
    
    # 高德地图，无IDFA
    pod 'AMap2DMap-NO-IDFA', '4.6.0'  # 2D地图SDK

end
